# Streamlit secrets configuration
# Add any API keys or sensitive configuration here

[github]
# If you need GitHub API access for automatic uploads
# token = "your_github_token_here"

[data_sources]
# Configure your data source URLs here
base_url = "https://raw.githubusercontent.com"
# Modify these URLs to match your GitHub repository
mcd43a3_url = "your-username/your-repo/main/outputs/csv/athabasca_mcd43a3_results.csv"
melt_season_url = "your-username/your-repo/main/outputs/csv/athabasca_melt_season_results.csv"
hypsometric_url = "your-username/your-repo/main/outputs/csv/athabasca_hypsometric_results.csv"